### ISSUE TITLE
Is there a way to read the pin mode?

### ISSUE THREAD

**Issue by dachshund-digital** [ahmed9378/pcf8574_io#2]
Is there a way to read the pin mode?  RPi.GPIO for example has the GPIO.gpio_function() feature, where you can get the pin mode from the RPi,GPIO configuration.  If such does not exist, could you add this to the solution?

**Comment by ahmed9378** [comment]
Check out the new features. You can find it on **test.py**

**Comment by ahmed9378** [comment]
@

**Comment by dachshund-digital** [comment]
Excellent!  Thanks.
