### ISSUE TITLE
Can't use new feature get_pin_mode?

### ISSUE THREAD

**Issue by dachshund-digital** [ahmed9378/pcf8574_io#3]
I have download the module, installed via python3 setup.py install, successful, then tried to use the new function get_pin_mode, and the resulting error I get is 'PCF' object has no attribute 'get_pin_mode'.  I confirmed it is the latest version.

Tail of the install...

creating 'dist/pcf8574_io-0.1.1-py3.7.egg' and adding 'build/bdist.linux-armv6l/egg' to it
removing 'build/bdist.linux-armv6l/egg' (and everything under it)
Processing pcf8574_io-0.1.1-py3.7.egg
Copying pcf8574_io-0.1.1-py3.7.egg to /usr/local/lib/python3.7/dist-packages
Adding pcf8574-io 0.1.1 to easy-install.pth file

Installed /usr/local/lib/python3.7/dist-packages/pcf8574_io-0.1.1-py3.7.egg
Processing dependencies for pcf8574-io==0.1.1
Searching for smbus2==0.4.1
Best match: smbus2 0.4.1
Adding smbus2 0.4.1 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Finished processing dependencies for pcf8574-io==0.1.1

Any ideas?

**Comment by dachshund-digital** [comment]
Something is not setup right...  When I do help(pcf8574_io) there is no reference to the new function get_pin_mode...

Help on package pcf8574_io:

NAME
    pcf8574_io

PACKAGE CONTENTS
    PCF85

CLASSES
    builtins.object
        PCF

    class PCF(builtins.object)
     |  PCF(address)
     |
     |  Methods defined here:
     |
     |  __init__(self, address)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  digital_read(self, PinName)
     |
     |  digital_write(self, PinName, Val)
     |
     |  pin_mode(self, PinName, Mode)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

FILE
    /usr/local/lib/python3.7/dist-packages/pcf8574_io/__init__.py

**Comment by dachshund-digital** [comment]
Using your published example... I can't any of the class functions directly in appears...

Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcf8574_io
>>> p1=pcf8574_io.PCF(0x38)
>>> p1.pin_mode("p0", "INPUT")
>>> print(p1.read("p0"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PCF' object has no attribute 'read'

But I can use the exposed functions...

Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcf8574_io
>>> p1=pcf8574_io.PCF(0x38)
>>> p1.pin_mode("p0", "INPUT")
>>> print(p1.digital_read("p0"))
True

So what do I need to do to get to direct class functions?  Or can you expose them correctly?

**Comment by ahmed9378** [comment]
It seems like you are still running on the old version, 0.0.6. Please make sure you delete it, then install the package using pip3 `pip3 install pcf8574_io`. I personally used `pip3 uninstall pcf8574_io` to remove the old package then install the new one, and it is working perfectly.  You can also use the following `pip3 install pcf8574-io --upgrade` to upgrade the package directly without uninstalling it.

**Comment by dachshund-digital** [comment]
Will give this a try.

    # pip3 uninstall pcf8574_io
    Found existing installation: pcf8574-io 0.0.6
    Uninstalling pcf8574-io-0.0.6:
      Would remove:
        /usr/local/lib/python3.7/dist-packages/pcf8574_io-0.0.6.dist-info/*
        /usr/local/lib/python3.7/dist-packages/pcf8574_io/*
    Proceed (y/n)? y
      Successfully uninstalled pcf8574-io-0.0.6

Then...

    # pip3 install pcf8574_io
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Requirement already satisfied: pcf8574_io in /usr/local/lib/python3.7/dist-packages/pcf8574_io-0.1.1-py3.7.egg (0.1.1)
    Requirement already satisfied: smbus2 in /usr/local/lib/python3.7/dist-packages (from pcf8574_io) (0.4.1)

Then...

    # python3
    >>> import pcf8575_io
    >>> dir(pcf8574_io)
    ['PCF', 'PCF85', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
    >>> t.pin_mode("p0", "INPUT")
    >>> t.read("p0")
    True
    >>> t.get_pin_mode("p0")
    'INPUT'`

So looks like I got the right version on the re-install.  Thanks!
